### ISSUE TITLE
Add diagram explaining how the CODE works? (under the hood)

### ISSUE THREAD

**Issue by nelsonic** [ideaq/faster#29]
@iteles while you are reviewing https://github.com/ideaq/faster/pull/26
please let me know if a diagram would help others understand how this module works (_under the hood_) ...

**Comment by iteles** [comment]
I think it would so that you don't have to keep moving back and forward between modules. I know how those 4 extra modules work but a visual reminder is easier to load into memory (for most people) as you're reviewing the code than a description of the interaction with each.

**Comment by nelsonic** [comment]
Well volunteered! :+1: :stuck_out_tongue_winking_eye:

**Comment by iteles** [comment]
I thought that might happen :grimacing:

**Comment by nelsonic** [comment]
Its a waste of your time. I will do it after my next item is complete.

**Comment by nelsonic** [comment]
Done. 👍
