### ISSUE TITLE
Remove refresh bar from bottom of screen?

### ISSUE THREAD

**Issue by iteles** [ideaq/faster#43]
The refresh bar ends up covering the bottom section of the screen and doesn't allow people to properly view what they're trying to run. I would suggest that this would be more useful if it was switched on and off from the admin panel #40 :blush: 
![faster-refresh-bar-covers-screen](https://cloud.githubusercontent.com/assets/4185328/6948997/9a3ca502-d8a9-11e4-87fb-b03bb271e8e2.png)

**Comment by nelsonic** [comment]
@iteles agree. its an eye-sore. it was just a first draft. will remove it.

**Comment by nelsonic** [comment]
This was done ages ago. forgot to close...
