### ISSUE TITLE
CSS Framework for Rapid Development?

### ISSUE THREAD

**Issue by nelsonic** [ideaq/faster#44]
The Admin Panel  #40 does not need to be "_unique_" it just needs to be _functional_ yet _attractive_.
For this, I propose using [**Foundation**](http://foundation.zurb.com). 
@iteles any thoughts? 
@tonydaly what are the cool kids using these days...? :wink:

**Comment by iteles** [comment]
Agreed, let's sketch something upfront so we can [customise our Foundation styles](http://foundation.zurb.com/develop/download.html#customizeFoundation) to as bare bones as possible with these things (or whatever else we decide to use, as long as it's not Bootstrap)

**Comment by nelsonic** [comment]
Goto: https://github.com/dwyl/learn-tachyons
and: https://github.com/dwyl/tachyons-bootstrap
