### ISSUE TITLE
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource

### ISSUE THREAD

**Issue by nelsonic** [ideaq/faster#54]
Getting the following error in 

## Firefox on Mac `60.0.2 (64-bit)`
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at ‘http://localhost:4242/socket.io/?EIO=3&transport=polling&t=MFc5fYF’. (Reason: Credential is not supported if the CORS header ‘Access-Control-Allow-Origin’ is ‘*’).
```
![image](https://user-images.githubusercontent.com/194400/41195518-ab514fd2-6c26-11e8-80bc-95b7e968103b.png)

## Chrome `Version 67.0.3396.79 (Official Build) (64-bit)`
```
localhost/:1 Failed to load http://localhost:4242/socket.io/?EIO=3&transport=polling&t=MFc6VsO: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. Origin 'http://localhost:4000' is therefore not allowed access. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.
```
![image](https://user-images.githubusercontent.com/194400/41195532-dd6507a2-6c26-11e8-8f93-7ff89f9ab696.png)

**Comment by nelsonic** [comment]
Reading this: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

**Comment by ghost** [comment]
go to your browser settings and click on adds-ons -> Extensions -> then search for "CORS Everywhare" add it to your browser

**Comment by nelsonic** [comment]
@the1Spartacus thanks for sharing your answer to this issue! 🎉

**Comment by mohit61** [comment]
@the1Spartacus awesome.

**Comment by holgerco** [comment]
@the1Spartacus awesome. thank a lot

**Comment by moxixuan** [comment]
@the1Spartacus thank you so much

**Comment by blappa** [comment]
what about if that error come from cloud function written in python ?

**Comment by cloudlakecho** [comment]
> go to your browser settings and click on adds-ons -> Extensions -> then search for "CORS Everywhare" add it to your browser

Isn't there a security issue in the solution? I found [How to launch html using Chrome at “--allow-file-access-from-files” mode?](https://stackoverflow.com/questions/18586921/how-to-launch-html-using-chrome-at-allow-file-access-from-files-mode/33801287#33801287l)
